
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sql;

/** CUP generated class containing symbol constants. */
public class SimpleSqlParserSym {
  /* terminals */
  public static final int WHERE = 18;
  public static final int FROM = 3;
  public static final int AND = 10;
  public static final int DESC = 17;
  public static final int SELECT = 2;
  public static final int OR = 11;
  public static final int RPAREN = 7;
  public static final int OP = 9;
  public static final int ON = 12;
  public static final int ORDER = 14;
  public static final int AS = 4;
  public static final int LPAREN = 6;
  public static final int LIMIT = 23;
  public static final int RIGHT = 22;
  public static final int LEFT = 21;
  public static final int COMMA = 5;
  public static final int INNER = 20;
  public static final int FUNC = 19;
  public static final int EOF = 0;
  public static final int BY = 15;
  public static final int error = 1;
  public static final int ASC = 16;
  public static final int TOKEN = 24;
  public static final int JOIN = 8;
  public static final int GROUP = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "FROM",
  "AS",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "JOIN",
  "OP",
  "AND",
  "OR",
  "ON",
  "GROUP",
  "ORDER",
  "BY",
  "ASC",
  "DESC",
  "WHERE",
  "FUNC",
  "INNER",
  "LEFT",
  "RIGHT",
  "LIMIT",
  "TOKEN"
  };
}

